general.import = [
    "~/.config/alacritty/catppuccin-mocha.toml"
]

[font]
size = 18.0 

[font.bold]
family = "Hack Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Hack Nerd Font"
style = "Bold Italic"

[font.italic]
family = "Hack Nerd Font"
style = "Italic"

[font.normal]
family = "Hack Nerd Font"
style = "Regular"

[window]
# opacity = 0.6
blur = true
startup_mode = "Maximized"
decorations = "Buttonless"

[cursor]
style = {shape = "Underline", blinking = "On"}

[env]
TERM = "xterm-256color"

[keyboard]
bindings = [
  { key = "N", mods = "Control|Shift", action = "CreateNewWindow" }
]
