general.import = [
    "~/.config/alacritty/catppuccin-mocha.toml"
]

[font]
size = 24.0 

[font.bold]
family = "Hack Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Hack Nerd Font"
style = "Bold Italic"

[font.italic]
family = "Hack Nerd Font"
style = "Italic"

[font.normal]
family = "Hack Nerd Font"
style = "Regular"

[window]
# opacity = 0.6
blur = true
startup_mode = "Maximized"
decorations = "Buttonless"

[cursor]
style = {shape = "Underline", blinking = "On"}

[env]
TERM = "xterm-256color"

[keyboard]
bindings = [
  { key = "N", mods = "Control|Shift", action = "CreateNewWindow" },
  { key = "Key1", mods = "Alt", chars = "\u001b1" },
  { key = "Key2", mods = "Alt", chars = "\u001b2" },
  { key = "Key3", mods = "Alt", chars = "\u001b3" },
  { key = "Key4", mods = "Alt", chars = "\u001b4" },
  { key = "Key5", mods = "Alt", chars = "\u001b5" },
]
